
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "and id not number orprg : atribsatribs : atribatribs : atribs atribatrib : id '=' expCondexpCond : expexpCond : exp '=' '=' expexp : termexp : exp '+' termexp : exp or termterm : factterm : term '*' factfact : numberfact : '(' expCond ')'fact : id"
    
_lr_action_items = {'id':([0,2,3,5,6,7,8,9,10,11,12,13,15,16,17,19,20,21,22,23,24,],[4,4,-2,-3,7,-14,-4,-5,-7,-10,-12,7,7,7,7,7,-8,-9,-11,-13,-6,]),'$end':([1,2,3,5,7,8,9,10,11,12,20,21,22,23,24,],[0,-1,-2,-3,-14,-4,-5,-7,-10,-12,-8,-9,-11,-13,-6,]),'=':([4,7,9,10,11,12,14,20,21,22,23,],[6,-14,14,-7,-10,-12,19,-8,-9,-11,-13,]),'number':([6,13,15,16,17,19,],[12,12,12,12,12,12,]),'(':([6,13,15,16,17,19,],[13,13,13,13,13,13,]),'*':([7,10,11,12,20,21,22,23,],[-14,17,-10,-12,17,17,-11,-13,]),'+':([7,9,10,11,12,20,21,22,23,24,],[-14,15,-7,-10,-12,-8,-9,-11,-13,15,]),'or':([7,9,10,11,12,20,21,22,23,24,],[-14,16,-7,-10,-12,-8,-9,-11,-13,16,]),')':([7,9,10,11,12,18,20,21,22,23,24,],[-14,-5,-7,-10,-12,23,-8,-9,-11,-13,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prg':([0,],[1,]),'atribs':([0,],[2,]),'atrib':([0,2,],[3,5,]),'expCond':([6,13,],[8,18,]),'exp':([6,13,19,],[9,9,24,]),'term':([6,13,15,16,19,],[10,10,20,21,10,]),'fact':([6,13,15,16,17,19,],[11,11,11,11,22,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prg","S'",1,None,None,None),
  ('prg -> atribs','prg',1,'p_prg1','gt.py',6),
  ('atribs -> atrib','atribs',1,'p_atribs1','gt.py',11),
  ('atribs -> atribs atrib','atribs',2,'p_atribs2','gt.py',16),
  ('atrib -> id = expCond','atrib',3,'p_atrib','gt.py',21),
  ('expCond -> exp','expCond',1,'p_expCond1','gt.py',29),
  ('expCond -> exp = = exp','expCond',4,'p_expCond2','gt.py',34),
  ('exp -> term','exp',1,'p_exp1','gt.py',39),
  ('exp -> exp + term','exp',3,'p_exp2','gt.py',44),
  ('exp -> exp or term','exp',3,'p_exp3','gt.py',49),
  ('term -> fact','term',1,'p_term1','gt.py',54),
  ('term -> term * fact','term',3,'p_term2','gt.py',59),
  ('fact -> number','fact',1,'p_fact1','gt.py',64),
  ('fact -> ( expCond )','fact',3,'p_fact2','gt.py',69),
  ('fact -> id','fact',1,'p_fact3','gt.py',74),
]
